typedef enum KeyboardKey {
    KeyboardKey_NULL          = 0, // Key: NULL, used for no key pressed
    // Alphanumeric keys
    KeyboardKey_APOSTROPHE    = 39, // Key: '
    KeyboardKey_COMMA         = 44, // Key: ,
    KeyboardKey_MINUS         = 45, // Key: -
    KeyboardKey_PERIOD        = 46, // Key: .
    KeyboardKey_SLASH         = 47, // Key: /
    KeyboardKey_ZERO          = 48, // Key: 0
    KeyboardKey_ONE           = 49, // Key: 1
    KeyboardKey_TWO           = 50, // Key: 2
    KeyboardKey_THREE         = 51, // Key: 3
    KeyboardKey_FOUR          = 52, // Key: 4
    KeyboardKey_FIVE          = 53, // Key: 5
    KeyboardKey_SIX           = 54, // Key: 6
    KeyboardKey_SEVEN         = 55, // Key: 7
    KeyboardKey_EIGHT         = 56, // Key: 8
    KeyboardKey_NINE          = 57, // Key: 9
    KeyboardKey_SEMICOLON     = 59, // Key: ;
    KeyboardKey_EQUAL         = 61, // Key: =
    KeyboardKey_A             = 65, // Key: A | a
    KeyboardKey_B             = 66, // Key: B | b
    KeyboardKey_C             = 67, // Key: C | c
    KeyboardKey_D             = 68, // Key: D | d
    KeyboardKey_E             = 69, // Key: E | e
    KeyboardKey_F             = 70, // Key: F | f
    KeyboardKey_G             = 71, // Key: G | g
    KeyboardKey_H             = 72, // Key: H | h
    KeyboardKey_I             = 73, // Key: I | i
    KeyboardKey_J             = 74, // Key: J | j
    KeyboardKey_K             = 75, // Key: K | k
    KeyboardKey_L             = 76, // Key: L | l
    KeyboardKey_M             = 77, // Key: M | m
    KeyboardKey_N             = 78, // Key: N | n
    KeyboardKey_O             = 79, // Key: O | o
    KeyboardKey_P             = 80, // Key: P | p
    KeyboardKey_Q             = 81, // Key: Q | q
    KeyboardKey_R             = 82, // Key: R | r
    KeyboardKey_S             = 83, // Key: S | s
    KeyboardKey_T             = 84, // Key: T | t
    KeyboardKey_U             = 85, // Key: U | u
    KeyboardKey_V             = 86, // Key: V | v
    KeyboardKey_W             = 87, // Key: W | w
    KeyboardKey_X             = 88, // Key: X | x
    KeyboardKey_Y             = 89, // Key: Y | y
    KeyboardKey_Z             = 90, // Key: Z | z
    KeyboardKey_LEFT_BRACKET  = 91, // Key: [
    KeyboardKey_BACKSLASH     = 92, // Key: '\'
    KeyboardKey_RIGHT_BRACKET = 93, // Key: ]
    KeyboardKey_GRAVE         = 96, // Key: `
    // Function keys
    KeyboardKey_SPACE         = 32,  // Key: Space
    KeyboardKey_ESCAPE        = 256, // Key: Esc
    KeyboardKey_ENTER         = 257, // Key: Enter
    KeyboardKey_TAB           = 258, // Key: Tab
    KeyboardKey_BACKSPACE     = 259, // Key: Backspace
    KeyboardKey_INSERT        = 260, // Key: Ins
    KeyboardKey_DELETE        = 261, // Key: Del
    KeyboardKey_RIGHT         = 262, // Key: Cursor right
    KeyboardKey_LEFT          = 263, // Key: Cursor left
    KeyboardKey_DOWN          = 264, // Key: Cursor down
    KeyboardKey_UP            = 265, // Key: Cursor up
    KeyboardKey_PAGE_UP       = 266, // Key: Page up
    KeyboardKey_PAGE_DOWN     = 267, // Key: Page down
    KeyboardKey_HOME          = 268, // Key: Home
    KeyboardKey_END           = 269, // Key: End
    KeyboardKey_CAPS_LOCK     = 280, // Key: Caps lock
    KeyboardKey_SCROLL_LOCK   = 281, // Key: Scroll down
    KeyboardKey_NUM_LOCK      = 282, // Key: Num lock
    KeyboardKey_PRINT_SCREEN  = 283, // Key: Print screen
    KeyboardKey_PAUSE         = 284, // Key: Pause
    KeyboardKey_F1            = 290, // Key: F1
    KeyboardKey_F2            = 291, // Key: F2
    KeyboardKey_F3            = 292, // Key: F3
    KeyboardKey_F4            = 293, // Key: F4
    KeyboardKey_F5            = 294, // Key: F5
    KeyboardKey_F6            = 295, // Key: F6
    KeyboardKey_F7            = 296, // Key: F7
    KeyboardKey_F8            = 297, // Key: F8
    KeyboardKey_F9            = 298, // Key: F9
    KeyboardKey_F10           = 299, // Key: F10
    KeyboardKey_F11           = 300, // Key: F11
    KeyboardKey_F12           = 301, // Key: F12
    KeyboardKey_LEFT_SHIFT    = 340, // Key: Shift left
    KeyboardKey_LEFT_CONTROL  = 341, // Key: Control left
    KeyboardKey_LEFT_ALT      = 342, // Key: Alt left
    KeyboardKey_LEFT_SUPER    = 343, // Key: Super left
    KeyboardKey_RIGHT_SHIFT   = 344, // Key: Shift right
    KeyboardKey_RIGHT_CONTROL = 345, // Key: Control right
    KeyboardKey_RIGHT_ALT     = 346, // Key: Alt right
    KeyboardKey_RIGHT_SUPER   = 347, // Key: Super right
    KeyboardKey_KB_MENU       = 348, // Key: KB menu
    // Keypad keys
    KeyboardKey_KP_0          = 320, // Key: Keypad 0
    KeyboardKey_KP_1          = 321, // Key: Keypad 1
    KeyboardKey_KP_2          = 322, // Key: Keypad 2
    KeyboardKey_KP_3          = 323, // Key: Keypad 3
    KeyboardKey_KP_4          = 324, // Key: Keypad 4
    KeyboardKey_KP_5          = 325, // Key: Keypad 5
    KeyboardKey_KP_6          = 326, // Key: Keypad 6
    KeyboardKey_KP_7          = 327, // Key: Keypad 7
    KeyboardKey_KP_8          = 328, // Key: Keypad 8
    KeyboardKey_KP_9          = 329, // Key: Keypad 9
    KeyboardKey_KP_DECIMAL    = 330, // Key: Keypad .
    KeyboardKey_KP_DIVIDE     = 331, // Key: Keypad /
    KeyboardKey_KP_MULTIPLY   = 332, // Key: Keypad *
    KeyboardKey_KP_SUBTRACT   = 333, // Key: Keypad -
    KeyboardKey_KP_ADD        = 334, // Key: Keypad +
    KeyboardKey_KP_ENTER      = 335, // Key: Keypad Enter
    KeyboardKey_KP_EQUAL      = 336, // Key: Keypad =
    // Android key buttons
    KeyboardKey_BACK          = 4,  // Key: Android back button
    KeyboardKey_MENU          = 5,  // Key: Android menu button
    KeyboardKey_VOLUME_UP     = 24, // Key: Android volume up button
    KeyboardKey_VOLUME_DOWN   = 25  // Key: Android volume down button
} KeyboardKey;
